slogan: Tranquility Yields Transcendence.
email: example@email.com
logo: "/images/logo.svg"

mathjax: false # 加载 LateX 数学公式库

favicon: # 配置网页图标
  small: /images/favicon-16x16.png
  medium: /images/favicon-32x32.png
  apple_touch_icon: /images/apple-touch-icon.png
  safari_pinned_tab: /images/logo.svg

subpage: # 开启“子页”功能，详见 README
  enable: true
  pages:
    - name: featTest # 文章的分类（category）名，如 developer
      path: feat # 若不设置则默认使用 name
      title: Feat # 菜单名，如 开发者
      icon: /images/icon/icon-code.svg # 图标的路径
      description: Feature Test of The Theme # 描述
    - name: baseTest # 文章的分类（category）名，如 developer
      path: base # 若不设置则默认使用 name
      title: Base # 菜单名，如 开发者
      icon: /images/icon/icon-pi.svg # 图标的路径
      description: Base Test Base on Hexo official # 描述

index: # 配置首页个性化内容
  motto: "There will be times when the long winds break the waves!"
  poem:
    - Have you not seen the sorrow in the bright mirror as people lament their white hair?
    - In the morning it was like black silk, by evening it has turned to snow.
  photo: /images/about.jpg
  about:
    title: About
    text:
      - When the wine flows into the poet's guts, seven parts turn into moonlight,
      -
      - The remaining three parts roar into sword aura,
      -
      - A single breath from his embroidered lips captures half the grandeur of the flourishing Tang dynasty.

foot:
  title:
    - "Though Miles Apart,"
    - "Friends Are Close at Heart."
  linksRows: 4

links: # 朋友
  - name: "Theme Tranquility"
    url: https://github.com/hooozen/hexo-theme-tranquility
  - name: "浩然的主页"
    url: https://hozen.site
  - name: "Theme Tranquility"
    url: https://github.com/hooozen/hexo-theme-tranquility
  - name: "浩然的主页"
    url: https://hozen.site
  - name: "Theme Tranquility"
    url: https://github.com/hooozen/hexo-theme-tranquility
  - name: "浩然的主页"
    url: https://hozen.site
  - name: "Theme Tranquility"
    url: https://github.com/hooozen/hexo-theme-tranquility
  - name: "浩然的主页"
    url: https://hozen.site
  - name: "Theme Tranquility"
    url: https://github.com/hooozen/hexo-theme-tranquility
  - name: "浩然的主页"
    url: https://hozen.site

social:
  - name: "hooozen"
    icon: "/images/logo-github.svg"
    url: https://github.com/hooozen
  - name: "谁在胡言乱语"
    icon: "/images/logo-wx.svg"
    url: https://mp.weixin.qq.com/s?__biz=MzI3NzQ4NDkzNg==&mid=2247484469&idx=1&sn=8a442bb67397f52cce5c38c3f9b41e36&chksm=eb64c0d2dc1349c40d2e1bb55615ae28b3f2951be22f00717b9ade98c851082e42dc666ab45d#rd
  - name: "Mundooo"
    icon: "/images/logo-zh.svg"
    url: https://www.zhihu.com/people/hozen

contacts:
  - name: "name@example.com"
    icon: "/images/icon/icon-email.svg"
    url: "mailto:name@example.com"

reward: # 赞赏
  enable: true
  face: /assets/author-face.jpg # 头像图片
  paycode: /assets/pay-code.jpg # 支付码图片
  text: \"Pour a cup of cappuccino for the author.\"
  btnText: Like The Author

# see https://github.com/gitalk/gitalk
gitalk: # gitalk 评论
  enable: false
  owner: # MUST HAVE, Your Github Username
  admin:
  repo: # MUST HAVE, The name of the repo you use to store Gitment comments
  clientID: # MUST HAVE, Github client id for the Gitment
  clientSecret: # EITHER this or proxy_gateway, Github access secret token for the Gitment

  distractionFreeMode: false # Facebook-like distraction free mode
  # When the official proxy is not available, you can change it to your own proxy address
  proxy: https://cors-anywhere.azm.workers.dev/https://github.com/login/oauth/access_token # This is official proxy adress
  # Gitalk's display language depends on user's browser or system environment
  # If you want everyone visiting your site to see a uniform language, you can set a force language value
  # Available values: en | es-ES | fr | ru | zh-CN | zh-TW
  language: zh-CN

# see https://github.com/tea3/hexo-related-popular-posts
related_post:
  enable: true
  config:
    maxCount: 5 # Maximum count of a list. default 5
    ulClass: # Class name of element. deafult 'popular-posts'
    PPMixingRate: 0.4 # Mixing ratio of popular posts and related posts. default 0.0(=Related posts only)
    isDate: # visible the date. false
    isImage: # visible the image. false
    isExcerpt: # visible the excerpt. false
    PPCategoryFilter: # Option to fix category on Popular Posts. undefined
    PPTagFilter: # Option to fix tag on Popular Posts. undefined

# Baidu Webmaster tools verification.
# See: https://ziyuan.baidu.com/site
baidu_site_verification:

# Baidu Analytics
# See: https://tongji.baidu.com
baidu_analytics: # <app_id>

# 自定义字体，用于美化部分汉字的显示效果.
# 可以通过替换 _font/ 目录下的字体文件替换自己喜欢的字体
zh_font:
  enable: true
  fontName: sourceHanSerif
  type: ttf
  style:
    - normal
    - bold

# 配置时间线 参考 README.md
timeline:
  enable: true
  order: false # 是否按时间正序展示，false 为倒序
  items:
    - name: article
      color: "#ee936c"
      icon: /images/icon/icon-article.svg
      checked: false
    - name: app
      color: "#60a465"
      icon: /images/icon/icon-app.svg
      checked: true
    - name: event
      color: "#568dc4"
      icon: /images/icon/icon-event.svg
      checked: false

# 标签云
tagcloud:
  fancy: false
  min_font: 14
  max_font: 30

mermaid:
  enable: true # 启用 Mermaid 增强
  version: latest
  options:
    startOnload: true

cv:
  enable: true
  showInNav: true
  iconPrefix: fas
  keywords: CV, Li Bai
  description: Li Bai's CV
  title: Li Bai's CV
  content:
    title: Li Bai
    baseInfo:
      - Tang Dynasty
      - Poet
      - Taibai
      - Qinglian Jushi
    tel: 88888
    email: libai@tang.chinese
    github: None
    blog: Tranquility
    blogHref: https://theme.hozen.site/tranquility/
    edu:
      title: "Education Background"
      content:
        - 701 to 715, Studied poetry and swordsmanship
        - 718 to 724, Lived in seclusion in Shu
    chapters:
      - title: "Representative Works"
        icon: person-digging
        tips: Click on the project name for details
        sections:
          - title: Difficulty in Shu Road
            link: https://so.gushiwen.cn/shiwenv_d59ec5d6c91c.aspx
            description: Yuefu Poem, Romanticism
            content:
              - First year of Tianbao
              - This poem reused an old Yuefu title and was intended to bid farewell to a friend going to Shu. The poet employs romanticist techniques, using rich imagination to artistically recreate the rugged, overpowering, and treacherous landscape of Shu Road, singing praises of Shu's majestic scenery and showcasing the grandeur of China's rivers and mountains.
              - The deeper meaning of this poem has been debated through the ages. While it doesn’t necessarily need a symbolic interpretation, the line “the officials may not be kin, turning into wolves and tigers” serves as a caution to guard the crucial region of Shu properly. The poem uses a mix of regulated and unrhymed styles, with varied lines and free-flowing thoughts, creating a forceful and evocative read that stirs deep emotions.
          - title: Bring in the Wine
            link: https://so.gushiwen.cn/shiwenv_ee16df5673bc.aspx
            description: Yuefu Seven-character Song
            content:
              - 22nd year of Kaiyuan
              - This poem was written while Li Bai was visiting his friend Cen Xun and another old friend Yuan Danqiu at his Yingyang mountain residence in Song Mountain. Going through career setbacks, Li Bai expressed his emotions through a joyful and unrestrained poetic outpour. In this poem, he uses the theme of wine to vent his sorrows and lament the fleeting nature of life and his unrecognized talent.
              - Most vividly, this poem reflects Li Bai's proud and unyielding character: confident, aloof, passionate, and unrestrained. Phrases like "A talent born will be of use" and "One must take all joy while alive" showcase an exuberant and infectious spirit. Li Bai's wine-themed poetry epitomizes his personality, with deep thematic content and mature artistic expression. "Bring in the Wine" stands as a representative piece of his work.
      - title: Work Experience
        icon: laptop-code
        sections:
          - title: Hanlin Official of the Tang Dynasty
            description: 743 - 744
            content:
              - Bestowed a brocade robe. In late spring, with peonies blooming by Xingqing Pond, Emperor Xuanzong, along with Yang Yuhuan, admired the flowers while Li Bai was commanded to write the "Qingping Melody". Gradually tired of the court poet's life, he began to indulge heavily in alcohol.
              - Became part of the “Eight Immortals of the Wine Cup” with He Zhizhang and others. When called by the Emperor, he often did not attend court duties. Once, he was summoned to draft an imperial edict while drunk, and famously made the eunuch Gao Lishi remove his boots. This led to resentment in the palace, and he was slandered before the emperor, who distanced him and eventually granted him gold to leave the court.
      - title: Honors and Awards
        icon: trophy
        list: true
        content:
          - Immortal Poet
          - One of the Eight Immortals of the Wine Cup
      - title: Personal Summary
        icon: ranking-star
        content:
          - Cheerful and generous, loves making friends, passionate about drinking wine and composing poetry, and honored as one of the “Eight Immortals of the Wine Cup.” Recognized by Emperor Xuanzong of the Tang Dynasty, he served as an imperial scholar, was bestowed gold, traveled extensively, and married the granddaughters of chancellors Xu Yushi and Zong Chuke. During Emperor Suzong's reign, he got entangled in the Yongwang Rebellion and was exiled to Ye Lang, eventually reaching Li Yangbing's residence in Dangtu County. He passed away in the second year of Shangyuan at the age of sixty-two.
          - Authored "The Collected Works of Li Bai". Famous works include "Viewing the Waterfall at Mount Lu", "Hard Road to Travel", "Difficulty in Shu Road", "Bring in the Wine", and "Setting off from Baidi Town at Dawn". Li Bai's poetry enjoys an extremely high status for its innovative approach and artistic accomplishment, earning him the title of "Immortal Poet". Along with Du Fu, he is recognized as one of the greatest poets in Chinese literary history, often referred to as "Li-Du".

search:
  path: search.json
  enable: true
  field: post
  content: true

nav:
  sticky: false

google_ad:
  enable: true
  meta_tag: ca-pub-7713704413230895 # Google Analytics meta tag
