slogan: “宁静致远”
email: example@email.com
logo: "/images/logo.svg"

mathjax: false # 加载 LateX 数学公式库

favicon: # 配置网页图标
  small: /images/favicon-16x16.png
  medium: /images/favicon-32x32.png
  apple_touch_icon: /images/apple-touch-icon.png
  safari_pinned_tab: /images/logo.svg

subpage: # 开启“子页”功能，详见 README
  enable: true
  pages:
    - name: featTest # 文章的分类（category）名，如 developer
      path: feat # 若不设置则默认使用 name
      title: 特性测试 # 菜单名，如 开发者
      icon: /images/icon/icon-code.svg # 图标的路径
      description: 主题的功能测试 # 描述
    - name: baseTest # 文章的分类（category）名，如 developer
      path: base # 若不设置则默认使用 name
      title: 基础测试 # 菜单名，如 开发者
      icon: /images/icon/icon-pi.svg # 图标的路径
      description: 基于 hexo 官方的基础测试 # 描述

index: # 配置首页个性化内容
  motto: "长风破浪会有时！"
  poem:
    - 君不见高堂明镜悲白发
    - 朝如青丝暮成雪
  photo: /images/about.jpg
  about:
    title: 关于
    text:
      - 酒入豪肠,七分酿成了月光
      -
      - 余下的三分啸成剑气
      -
      - 绣口一吐就半个盛唐

foot:
  title:
    - "海内存知己"
    - "天涯若比邻"

links: # 朋友
  - name: "Theme Tranquility"
    url: https://github.com/hooozen/hexo-theme-tranquility
  - name: "浩然的主页"
    url: https://hozen.site

social:
  - name: "hooozen"
    icon: "/images/logo-github.svg"
    url: https://github.com/hooozen
  - name: "谁在胡言乱语"
    icon: "/images/logo-wx.svg"
    url: https://mp.weixin.qq.com/s?__biz=MzI3NzQ4NDkzNg==&mid=2247484469&idx=1&sn=8a442bb67397f52cce5c38c3f9b41e36&chksm=eb64c0d2dc1349c40d2e1bb55615ae28b3f2951be22f00717b9ade98c851082e42dc666ab45d#rd
  - name: "Mundooo"
    icon: "/images/logo-zh.svg"
    url: https://www.zhihu.com/people/hozen

reward: # 赞赏
  enable: true
  face: /assets/author-face.jpg # 头像图片
  paycode: /assets/pay-code.jpg # 支付码图片
  text: “给作者倒杯卡布奇诺”
  btnText: 喜欢作者

# see https://github.com/gitalk/gitalk
gitalk: # gitalk 评论
  enable: false
  owner: # MUST HAVE, Your Github Username
  admin:
  repo: # MUST HAVE, The name of the repo you use to store Gitment comments
  clientID: # MUST HAVE, Github client id for the Gitment
  clientSecret: # EITHER this or proxy_gateway, Github access secret token for the Gitment

  distractionFreeMode: false # Facebook-like distraction free mode
  # When the official proxy is not available, you can change it to your own proxy address
  proxy: https://cors-anywhere.azm.workers.dev/https://github.com/login/oauth/access_token # This is official proxy adress
  # Gitalk's display language depends on user's browser or system environment
  # If you want everyone visiting your site to see a uniform language, you can set a force language value
  # Available values: en | es-ES | fr | ru | zh-CN | zh-TW
  language: zh-CN

# see https://github.com/tea3/hexo-related-popular-posts
related_post:
  enable: true
  config:
    maxCount: 5 # Maximum count of a list. default 5
    ulClass: # Class name of element. deafult 'popular-posts'
    PPMixingRate: 0.4 # Mixing ratio of popular posts and related posts. default 0.0(=Related posts only)
    isDate: # visible the date. false
    isImage: # visible the image. false
    isExcerpt: # visible the excerpt. false
    PPCategoryFilter: # Option to fix category on Popular Posts. undefined
    PPTagFilter: # Option to fix tag on Popular Posts. undefined

# Baidu Webmaster tools verification.
# See: https://ziyuan.baidu.com/site
baidu_site_verification:

# Baidu Analytics
# See: https://tongji.baidu.com
baidu_analytics: # <app_id>

# 自定义字体，用于美化部分汉字的显示效果.
# 可以通过替换 _font/ 目录下的字体文件替换自己喜欢的字体
zh_font:
  enable: true
  fontName: sourceHanSerif
  type: ttf
  style:
    - regular
    - bold

# 配置时间线 参考 README.md
timeline:
  enable: true
  order: false # 是否按时间正序展示，false 为倒序
  items:
    - name: article
      color: "#ee936c"
      icon: /images/icon/icon-article.svg
      checked: false
    - name: app
      color: "#60a465"
      icon: /images/icon/icon-app.svg
      checked: true
    - name: event
      color: "#568dc4"
      icon: /images/icon/icon-event.svg
      checked: false

# 标签云
tagcloud:
  fancy: false
  min_font: 14
  max_font: 30

cv:
  keywords: 前端,简历,前端开发,AI,软件工程师
  description: 李浩然的简历
  title: 李浩然的简历
  content:
    title: 李浩然
    baseInfo:
      - 2024 应届硕士
      - 前端开发
    tel: 13175116769
    email: Hozen@live.com
    github: hooozen
    blog: hozen.site
    blogHref: https://hozen.site
    edu:
      title: "教育背景"
      content:
        - 2021.9 至今，河北大学，统计学，硕士在读
        - 2014.9 至 2018.6，长安大学，软件工程，学士学位
    chapters:
      - title: "个人项目"
        icon:
          name: person-digging
          type: fas
        tips: 请点击项目名称查看项目详情
        sections:
          - title: picStitch
            link: https://ps.hozen.site
            description: 长图拼接 Web App
            content:
              - 2023/9 至今
              - "技术栈: Vue3+ts+vite+pinia, 移动 Web, Canvas, PWA"
              - 主要实现了 Web 端图片的编辑和保存、图片拖动排序等功能。在开发过程中实践了面向对象开发、移动端适配、Vue3 底层组件封装、HTML5 的 Canvas、Drag、SVG 等技术. 详情：hozen.site/archives/69/
          - title: Tranquility
            link: https://github.com/hooozen/hexo-theme-tranquility
            description: 响应式博客网站
            content:
              - 2022/12 至今, 80+ stars
              - "技术栈: Node, Web page"
              - 主要实现了个人主页展示、博客编写和发布、网站 SEO、评论赞赏等博客系统。涉及 Node 开发、响应式页面设计及开发、页面性能优化及 SEO、字体提取压缩等技术。开发过程中调试了许多开源插件, 并贡献了部分文档和代码。
          - title: 篮球裁判手势挑战
            description: 微信答题挑战小程序
            link: https://www.hozen.site/archives/59/
            content:
              - 2022/10 至今, 4k+ uv
              - "技术栈: 微信小程序, Serverless"
              - "主要实现小程序答题挑战的交互逻辑以及积分排名、题目难度自动学习更新等功能。涉及微信小程序开发、Serverless 应用、NoSQL 数据库、接口设计和封装、Token 管理等技术"
          - title: 其他
            link: https://steamcommunity.com/sharedfiles/filedetails/?id=2222111958
            content:
              - 基于 wallpaper engine 的桌面动态壁纸(18k订阅), 学术风博客系统, Web 你画我猜小游戏等。详情见 github.com/hooozen。
      - title: 工作经验
        icon:
          name: laptop-code
          type: fas
        sections:
          - title: 杭州税友软件集团有限公司
            description: 2018.7 - 2019.3
            content:
              - 主要参与公司 B 端报税系统及员工薪税服务系统的客户端开发, 基于 CEF 和 VUE 技术栈.
              - 作为主要成员参与了公司统一 UI 库的开发及文档和 Demo 开发, 基于 ElementUI 封装定制.
              - 业务能力得到 leader 认可, 和同事相处愉快, 获得部门年度最佳新人奖.
          - title: 兼职经验
            description: 2021 - 2022
            content:
              - 考研结束的假期参与了若干外包项目，主要涉及 Vue 技术栈的后台管理系统以及物联网创业项目的小程序和商品配送管理系统的开发。线上和需求以及后台开发人员进行合作, 得到同事和客户认可.
      - title: 奖项证书
        icon:
          name: trophy
          type: fas
        list: true
        content:
          - 第十八届中国研究生数学建模竞赛, 全国二等奖, 使用机器学习和神经网络解决 UWB 定位问题
          - 招商银行第七届 FinTech 竞赛(数据赛道), 61/3000 名, 客户金融产品配置行为预测
          - 全国计算机信息高新技术考试合格证书, 国家职业资格四级, 图形图像处理模块(Photoshop平台)
      - title: 个人小结
        icon:
          name: ranking-star
          type: fas
        content:
          - 软件工程和统计学交叉学科背景, 数学基础好, 学习能力强. 项目经验丰富, 善于中英文文献资料检索阅读, 解决问题的能力强. 热爱软件开发, 具备优秀的文档和制图能力, 喜欢知识分享和输出.
          - 爱好阅读和学习, 积极的人生观和性格, 愿意为优秀的产品和团队付出热情和努力.
